<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav role="navigation" class="navbar navbar-inverse navbar-fixed-top">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand"><?php echo $this->translate('Home Management System');?></a>
            </div>

            <!-- Collection of nav links and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="application/index/home"><?php echo $this->translate('Home');?></a></li>
                    
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="addressbook/index"><?php echo $this->translate('Address Book'); ?> <b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="addressbook/contact">Contacts</a></li>
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="finance/index"><?php echo $this->translate('Finances'); ?> <b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="finance/account">Accounts</a></li>
                            <li><a href="finance/company">Companies</a></li>
                            <li><a href="finance/currency">Currency</a></li>
                            <li><a href="finance/bill">Bills</a></li>
                            <li><a href="finance/reports">Reports</a></li>
                        </ul>
                    </li>                    
                </ul>
                
                <form class="navbar-form navbar-right" method="POST" action="/application/index/logout">
                    <button type="submit" class="btn btn-primary btn-danger">Logout</button>
                </form>
                
            </div>
        </nav>
        <?php echo $this->content ?>
    </body>
</html>
