<script>
    function ConfirmCancel()
    {
      var x = confirm("Are you sure you want to cancel your changes?");
      if (x)
          return true;
      else
        return false;
    }
</script>
<?php
    $action = "/application/index/create";
?>

<form class="form-horizontal" method="POST" action=<?php $action ?>>
    <div class="form-group">
        <label for="username" class="control-label col-xs-2">Username</label>
        <div class="col-xs-10">
            <input type="input" class="form-control" id="username" name="username" placeholder="Username">
        </div>
    </div>
    
    <div class="form-group">
        <label for="name" class="control-label col-xs-2">Name</label>
        <div class="col-xs-10">
            <input type="input" class="form-control" id="name" name="name"placeholder="Name">
        </div>
    </div>

    <div class="form-group">
        <label for="password" class="control-label col-xs-2">Password</label>
        <div class="col-xs-10">
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <div class="checkbox">
                <label><input id="enabled" id="enabled" type="checkbox"> Enabled</label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <a class="btn btn-danger" onClick="return ConfirmCancel()" role="button" href="/application/user">Cancel</a></td>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
</form>


